version: '2'
services:
  web:
    restart: "no"
    build: .
    links:
      - database
    ports:
      - "8000:8000"

  database:
    restart: "no"
    build: postgres/
    ports:
      - "5432:5432"
